In [1]:
import numpy as np

s = np.array(map(float, raw_input().split()))

print np.floor(s)
print np.ceil(s)
print np.rint(s)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
